version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=sqlite:////app/db/app.db
      - MONGO_HOST=mongod
      - MONGO_PORT=27017
    volumes:
      - ./db:/app/db
    depends_on:
      - mongod

  mongod:
    image: mongo:latest
    container_name: mongod
    ports:
      - "27017:27017"
    command: mongod
